echo "Hostname: $(hostname)"                              
echo "OS: $(uname -s)"                                
echo "CPU Usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')%" 
echo "RAM Usage: $(free | awk '/Mem/ {printf("%.2f"), $3/$2 * 100}')%"  
echo "Disk Usage: $(df -h / | awk 'NR==2 {print $5}')"